version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio_container
    ports:
      - "9000:9000"
      - "9090:9090"
    networks:
      - app-tier
    volumes:
      - /data/minio:/data
      - ./certs/:/certs
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminpass
      MINIO_DEFAULT_BUCKET: ecatalog-bucket
    command: server --console-address ":9090" /data --certs-dir /certs

  nginx:
    image: nginx:latest
    container_name: nginx_container
    hostname: 'nginx'
    ports:
      - "8443:8443"
      - "8444:8444"
    environment:
      - "VIRTUAL_PORT=8443"
    networks:
      - app-tier
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - ./certs/:/etc/certs/
volumes:
  minio_storage: {}

networks:
  app-tier:
    driver: bridge