spring:
  thymeleaf:
    prefix: classpath:/public/
    suffix: .html
  redis:
    url: rediss://localhost:6379
    password: securepass
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 50
        max-idle: 20
        min-idle: 5
        max-wait: 3000ms
    admin:
      pool:
        size: 5 # Размер пула для администраторов
  datasource:
    url: jdbc:postgresql://localhost:5432/ecatalog_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  cookie-token-key: '{"kty":"oct","k":"956PBFst1FguLr5irJD-aQ"}'
  csrf-token-key: "fbcf5345673e8404"
  secret-key: "d2d7a5b1c4e6f8a9b3c5d7e9f1a2b4c6d8e0f2a4b6c8d0e2f4a6b8c0d2e4f6"

google:
  recaptcha:
    secret: "6Ld0uBErAAAAAK-Pf-Iw7MMun6s9skrX1_mcLSU7"
    url: "https://www.google.com/recaptcha/api/siteverify"
    site-key: "6Ld0uBErAAAAAFRfBnNNFWk6ukiGHnxgzTJBigPo"

security:
  rate-limit:
    admin:
      max-requests: 1000  # Большой лимит для администраторов
      duration-min: 1
      block-duration-min: 0
    global:
      max-requests: 100
      duration-min: 1
      block-duration-min: 1
    public:
      max-requests: 50
      duration-min: 1
      block-duration-min: 1
    protected: # БД
      max-requests: 60
      duration-min: 1
      block-duration-min: 1
    critical:
      max-requests: 30
      duration-min: 1
      block-duration-min: 1
    endpoints:
      register:
        max-requests: 100
        duration-min: 1
        block-duration-min: 1
      upload:
        max-requests: 200
        duration-min: 1
        block-duration-min: 1
  captcha:
    enabled: true
    max-attempts: 3       # после скольки неудачных попыток блокировать
    block-duration-min: 1 # длительность блокировки в минутах
  allowed-origins:
    - "https://localhost:8443"
    - "https://127.0.0.1:8443"

backup:
  retention-days: 7  # хранить бэкапы 7 дней
  compression-level: 6  # уровень сжатия (1-9)

server:
  port: 8443
  http2:
    enabled: true
  ssl:
    key-store: classpath:docker-ecatalog_ru/certs/keystore.p12
    key-store-password: 12345
    key-alias: ecatalog

logging:
  level:
      org:
        springframework:
          security: debug
        thymeleaf:
          extras:
            springsecurity6: debug

minio:
  url: https://localhost:9000
  access:
    name: admin
    secret: adminpass
  bucket:
    name: ecatalog-bucket

redis:
  url: rediss://localhost:6379
  password: securepass