version: '3.8'

services:
  keycloak:
    container_name: keycloak-container
    build:
      context: .
      dockerfile: ../../../../Dockerfile.keycloak
    ports:
      - "8282:8080"
      - "8443:8443"
    restart: on-failure   # Перезапустить при сбое
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3   # Максимум попыток перезапуска
    volumes:
      - type: bind
        source: ./imports/realm-export.json
        target: /opt/keycloak/data/import/realm-export.json # Часть настроек восстановится
        read_only: true
      - type: bind
        source: ./certs   # Монтируем директорию с сертификатами
        target: /etc/x509/https/  # Путь, куда будут монтироваться сертификаты
        read_only: true
    command: [ "start-dev",
               "--import-realm",
               "--http-enabled=false",
               "--https-port=8443",
               "--https-certificate-file=/etc/x509/https/localhost.pem",
               "--https-certificate-key-file=/etc/x509/https/localhost-key.pem"
    ]