version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio_container
    ports:
      - "9000:9000"
      - "9090:9090"
    networks:
      - app-tier
    volumes:
      - minio_data:/data
      - ./certs:/root/.minio/certs  # Папка с вашими сертификатами
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-adminpass}
      MINIO_SERVER_URL: https://localhost:9000
    command: server --console-address ":9090" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: redis:7.0-alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - app-tier
    volumes:
      - redis_data:/data
      - ./certs:/usr/local/etc/redis/certs
    command: >
      redis-server
      --tls-port 6379
      --port 0
      --tls-cert-file /usr/local/etc/redis/certs/public.crt
      --tls-key-file /usr/local/etc/redis/certs/private.key
      --tls-ca-cert-file /usr/local/etc/redis/certs/public.crt
      --tls-auth-clients no
      --tls-replication yes
      --tls-cluster yes
      --tls-protocols "TLSv1.2 TLSv1.3"
      --requirepass ${REDIS_PASSWORD:-securepass}
      --maxclients 10000
      --timeout 30
      --tcp-keepalive 300
      --client-output-buffer-limit normal 0 0 0
      --client-output-buffer-limit replica 256mb 64mb 60
      --client-output-buffer-limit pubsub 32mb 8mb 60
      --latency-monitor-threshold 100
      --slowlog-log-slower-than 10000
      --slowlog-max-len 128
      --maxmemory 1gb
      --maxmemory-policy allkeys-lru
      --hz 10
      --activedefrag yes
      --lazyfree-lazy-eviction yes
      --lazyfree-lazy-expire yes
      --lazyfree-lazy-server-del yes
      --replica-lazy-flush yes
    healthcheck:
      test: [ "CMD", "redis-cli", "--tls", "--cacert", "/usr/local/etc/redis/certs/public.crt", "-a", "${REDIS_PASSWORD:-securepass}", "ping" ]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_data:
  redis_data:

networks:
  app-tier:
    driver: bridge