version: '3.8'

services:
  keycloak:
    container_name: keycloak-container
    build:
      context: .
      dockerfile: Dockerfile
      target: keycloak
    ports:
      - "8282:8080"
    restart: on-failure   # Перезапустить при сбое
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3   # Максимум попыток перезапуска
    volumes:
      - type: bind
        source: ./imports/realm-export.json
        target: /opt/keycloak/data/import/realm-export.json # Часть настроек восстановится
        read_only: true
    command: ["start-dev", "--import-realm"]