# Dockerfile
# Keycloak
FROM quay.io/keycloak/keycloak:latest AS keycloak

ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=adminpass

# MinIO
#FROM quay.io/minio/minio:latest AS minio
#
#ENV MINIO_ROOT_USER=minio
#ENV MINIO_ROOT_PASSWORD=miniopass