version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio_container
    ports:
      - "9000:9000"   # API порт
      - "9090:9090"   # Консольный порт
    networks:
      - app-tier
    volumes:
      - minio_data:/data
      - ./certs:/root/.minio/certs  # Правильный путь для сертификатов MinIO
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}            # С дефолтным значением
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-adminpass} # С дефолтным значением
      MINIO_SERVER_URL: https://localhost:9000              # Важно для консоли
    command: server --console-address ":9090" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_data:

networks:
  app-tier:
    driver: bridge